# Generated by Django 5.2.4 on 2025-07-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idregistrantdata', models.BigIntegerField()),
                ('groupreg', models.IntegerField()),
                ('regtype', models.IntegerField()),
                ('iddataregkhusustype', models.IntegerField()),
                ('idschooltypedata', models.IntegerField()),
                ('idschooljurusandata', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('idmajordata', models.IntegerField()),
                ('idcountrydata', models.IntegerField()),
                ('iddataprovinces', models.IntegerField()),
                ('iddataregencies', models.IntegerField()),
                ('ispaid', models.IntegerField()),
                ('paymentamount', models.BigIntegerField()),
            ],
        ),
    ]
