# Generated by Django 5.2.4 on 2025-07-27 17:41

import marketing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to=marketing_app.models.upload_to_data_folder)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('total_rows', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
