# Generated by Django 5.2.4 on 2025-07-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='groupreg',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='idcountrydata',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='iddataprovinces',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='iddataregencies',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='iddataregkhusustype',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='idmajordata',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='idregistrantdata',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='idschooljurusandata',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='idschooltypedata',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='ispaid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='paymentamount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='regtype',
            field=models.CharField(max_length=50),
        ),
    ]
