# Generated by Django 5.2.4 on 2025-07-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_app', '0002_alter_registrationdata_groupreg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='groupreg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='idcountrydata',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='iddataprovinces',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='iddataregencies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='iddataregkhusustype',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='idmajordata',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='idregistrantdata',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='idschooljurusandata',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='idschooltypedata',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='paymentamount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='regtype',
            field=models.IntegerField(),
        ),
    ]
