# Generated by Django 5.2.4 on 2025-07-26 17:07

import marketing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_app', '0004_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=marketing_app.models.upload_to_data_folder),
        ),
    ]
