# Generated by Django 5.2.4 on 2025-07-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_app', '0005_alter_document_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationData',
        ),
    ]
