# Generated by Django 5.2.4 on 2025-07-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_app', '0006_delete_registrationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
