# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iI7q4SXUNMDIt8Th4eru73dT61-RGU9N
"""

import pandas as pd
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

df = pd.read_csv('/content/2022_encoded_data.csv')

regtype_mapping = {
    1: "TEST EVENT (By City/Area)",
    2: "Jalur-1 TEST (Pre-Reg)",
    3: "Jalur-2 RAPOR",
    4: "Jalur-3 PRESTASI",
    5: "S-1 Profesional (Kelas Malam)",
    6: "S-1 Executive (Kelas Weekend)",
    7: "S-2-Graduate Program",
    8: "International (ASEAN",
    9: "International-1 (CHINA)",
    10: "Program-1 Social & Culture (Darmasiswa)",
    11: "Program-2 Short Term",
    12: "Program-3 Research Attacement",
    13: "Program-4 Internship",
    14: "Program-5 Special Assignment",
    15: "Jalur-4 ONLINE TEST",
    16: "Jalur-5 UTBK SBMPTN",
    17: "Jalur-6 Blended Learning",
    18: "Jalur Fast Track Program (Dual Degree)",
    19: "Jalur-7 UNBK",
    20: "Jalur-8 Khusus"
}

# Tambahkan nama regtype
df['regtype_name'] = df['regtype'].map(regtype_mapping)

# Hitung jumlah per tipe
regtype_counts = df['regtype_name'].value_counts().reset_index()
regtype_counts.columns = ['regtype_name', 'count']

# Visualisasi dengan Plotly
fig = px.bar(
    regtype_counts,
    x='regtype_name',
    y='count',
    title='Distribusi Tipe Pendaftaran',
    text_auto=True,
    color='count',
    color_continuous_scale='pinkyl'
)

# Styling tambahan
fig.update_layout(
    xaxis_title='Tipe Pendaftaran',
    yaxis_title='Jumlah Siswa',
    title_font=dict(size=20, color='darkmagenta'),
    xaxis_tickangle=-30
)

fig.show()

"""# Ubah ID type asal sekolah"""

# Mapping tipe sekolah
schooltype_mapping = {
    1: "SMA",
    2: "SMK",
    3: "MA",
    9: "Lainnya"
}

# Tambahkan kolom nama tipe sekolah
df['schooltype_name'] = df['idschooltypedata'].map(schooltype_mapping)

# Hitung jumlah masing-masing tipe
schooltype_counts = df['schooltype_name'].value_counts().reset_index()
schooltype_counts.columns = ['schooltype_name', 'count']

# Visualisasi dengan Plotly
fig = px.bar(
    schooltype_counts,
    x='schooltype_name',
    y='count',
    title='Distribusi Tipe Sekolah Asal',
    text_auto=True,
    color='count',
    color_continuous_scale='RdPu'  # warna pink yang lembut
)

# Styling
fig.update_layout(
    xaxis_title='Tipe Sekolah',
    yaxis_title='Jumlah Siswa',
    title_font=dict(size=18, color='black'),
    xaxis_tickangle=0
)

fig.show()

"""# Distribusi ispaid"""

# Load data
df = pd.read_csv("2022_encoded_data.csv")

# Hitung jumlah masing-masing kategori pembayaran
payment_counts = df['ispaid'].value_counts().sort_index()

# Label dan warna
labels = ['Belum Melakukan Payment', 'Sudah Payment']
colors = ['#f7c6d9', '#ec407a']  # pastel pink dan pink cerah

# Pie chart dengan Plotly
fig = go.Figure(
    data=[
        go.Pie(
            labels=labels,
            values=payment_counts,
            marker=dict(colors=colors),
            textinfo='percent+label',
            insidetextorientation='radial',
            textfont=dict(size=14, color='black')
        )
    ]
)

fig.update_layout(
    title_text='Distribusi Siswa yang Sampai Tahap Payment',
    title_font=dict(size=18, color='black'),
    showlegend=False
)

fig.show()

"""# Merubah & Mapping data dari ID provinsi"""

# Mapping nama provinsi
province_mapping = {
    0: "Tidak Diketahui", 11: "Aceh", 12: "Sumatera Utara", 13: "Sumatera Barat",
    14: "Riau", 15: "Jambi", 16: "Sumatera Selatan", 17: "Bengkulu", 18: "Lampung",
    19: "Kepulauan Bangka Belitung", 21: "Kepulauan Riau", 31: "DKI Jakarta",
    32: "Jawa Barat", 33: "Jawa Tengah", 34: "DI Yogyakarta", 35: "Jawa Timur",
    36: "Banten", 51: "Bali", 52: "Nusa Tenggara Barat", 53: "Nusa Tenggara Timur",
    61: "Kalimantan Barat", 62: "Kalimantan Tengah", 63: "Kalimantan Selatan",
    64: "Kalimantan Timur", 65: "Kalimantan Utara", 71: "Sulawesi Utara",
    72: "Sulawesi Tengah", 73: "Sulawesi Selatan", 74: "Sulawesi Tenggara",
    75: "Gorontalo", 76: "Sulawesi Barat", 81: "Maluku", 82: "Maluku Utara",
    91: "Papua Barat", 94: "Papua"
}

# Mapping provinsi
df['province_name'] = df['iddataprovinces'].astype(int).map(province_mapping)

# Hitung jumlah pendaftar per provinsi
province_counts = df['province_name'].value_counts().reset_index()
province_counts.columns = ['province_name', 'jumlah_pendaftar']

# Plot dengan Plotly
fig = px.bar(
    province_counts,
    x='province_name',
    y='jumlah_pendaftar',
    title='Distribusi Pendaftar per Provinsi',
    text_auto=True,
    color='jumlah_pendaftar',
    color_continuous_scale='PuRd'  # gradasi pink elegan
)

fig.update_layout(
    xaxis_title='Provinsi',
    yaxis_title='Jumlah Pendaftar',
    title_font=dict(size=18, color='black'),
    xaxis_tickangle=-90
)

fig.show()

"""# Mendistribusikan UMP per provinsi"""

# --- 2. Mapping Provinsi ---
province_mapping = {
    0: "Tidak Diketahui", 11: "Aceh", 12: "Sumatera Utara", 13: "Sumatera Barat",
    14: "Riau", 15: "Jambi", 16: "Sumatera Selatan", 17: "Bengkulu", 18: "Lampung",
    19: "Kepulauan Bangka Belitung", 21: "Kepulauan Riau", 31: "DKI Jakarta",
    32: "Jawa Barat", 33: "Jawa Tengah", 34: "DI Yogyakarta", 35: "Jawa Timur",
    36: "Banten", 51: "Bali", 52: "Nusa Tenggara Barat", 53: "Nusa Tenggara Timur",
    61: "Kalimantan Barat", 62: "Kalimantan Tengah", 63: "Kalimantan Selatan",
    64: "Kalimantan Timur", 65: "Kalimantan Utara", 71: "Sulawesi Utara",
    72: "Sulawesi Tengah", 73: "Sulawesi Selatan", 74: "Sulawesi Tenggara",
    75: "Gorontalo", 76: "Sulawesi Barat", 81: "Maluku", 82: "Maluku Utara",
    91: "Papua Barat", 94: "Papua"
}
df['province_name'] = df['iddataprovinces'].map(province_mapping)

# --- 3. Pastikan Kolom UMP dalam Rupiah ---
# Buang nilai UMP yang terlalu besar (contoh: > 100 juta berarti salah satuan)
df = df[df['ump'] < 100_000_000]  # filter nilai absurd

# --- 4. Hitung Rata-rata UMP per Provinsi ---
ump_per_province = df.groupby('province_name')['ump'].mean().dropna().sort_values()

# --- 5. Plotly Bar Chart Horizontal ---
fig = go.Figure(
    go.Bar(
        x=ump_per_province.values,
        y=ump_per_province.index,
        orientation='h',
        marker=dict(
            color=ump_per_province.values,
            colorscale='RdPu'
        ),
        text=[f"Rp {int(x):,}".replace(",", ".") for x in ump_per_province.values],
        textposition='outside',
        hovertemplate='%{y}<br>UMP: Rp %{x:,.0f}<extra></extra>'
    )
)

fig.update_layout(
    title='UMP 2022 per Provinsi (dalam Rupiah)',
    xaxis_title='Nominal UMP (Rp)',
    yaxis_title='Provinsi',
    title_font=dict(size=18, color='black'),
    xaxis_tickformat=',.0f',
    margin=dict(l=80, r=50, t=80, b=50),
    height=850
)

fig.show()